"""empty message

Revision ID: 734083ad8770
Revises: 1ce94d65e152
Create Date: 2023-06-07 01:45:30.205674

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '734083ad8770'
down_revision = '1ce94d65e152'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fav__people',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('characeteres_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['characeteres_id'], ['peoples.characeteres_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'characeteres_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fav__people')
    # ### end Alembic commands ###
