"""empty message

Revision ID: d3535866b1e2
Revises: c3e133c71a44
Create Date: 2023-06-07 01:10:56.843777

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd3535866b1e2'
down_revision = 'c3e133c71a44'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('people',
    sa.Column('characeteres_id', sa.Integer(), nullable=False),
    sa.Column('name_people', sa.String(length=120), nullable=False),
    sa.Column('age', sa.String(length=80), nullable=False),
    sa.Column('born_date', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('characeteres_id'),
    sa.UniqueConstraint('name_people')
    )
    op.create_table('planet',
    sa.Column('planet_id', sa.Integer(), nullable=False),
    sa.Column('name_planet', sa.String(length=120), nullable=False),
    sa.Column('population', sa.String(length=80), nullable=False),
    sa.Column('climate', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('planet_id'),
    sa.UniqueConstraint('name_planet')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('planet')
    op.drop_table('people')
    # ### end Alembic commands ###
